# Generated by Django 6.0.2 on 2026-02-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='flowers/'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
